package pasa.cbentley.core.src4.utils;

import pasa.cbentley.core.src4.utils.interfaces.IColorsBase;
import pasa.cbentley.core.src4.utils.interfaces.IColorsWeb;

public class ColorStringBase implements IColorsBase, IColorsWeb {

   public static String getNameWeb(int rgb) {
      rgb = ColorUtils.setAlpha(rgb, 0);
      switch (rgb) {
         case WEB_antiquewhite:
            return "WEB_antiquewhite";
         case WEB_aliceblue:
            return "WEB_aliceblue";
         case WEB_aqua:
            return "WEB_aqua";
         case WEB_aquamarine:
            return "WEB_aquamarine";
         case WEB_azure:
            return "WEB_azure";
         case WEB_bisque:
            return "WEB_bisque";
         case WEB_black:
            return "WEB_black";
         case WEB_blanchedalmond:
            return "WEB_blanchedalmond";
         case WEB_blue:
            return "WEB_blue";
         case WEB_blueviolet:
            return "WEB_blueviolet";
         case WEB_brown:
            return "WEB_brown";
         case WEB_burlywood:
            return "WEB_burlywood";
         case WEB_cadetblue:
            return "WEB_cadetblue";
         case WEB_chartreuse:
            return "WEB_chartreuse";
         case WEB_chocolate:
            return "WEB_chocolate";
         case WEB_coral:
            return "WEB_coral";
         case WEB_cornflowerblue:
            return "WEB_cornflowerblue";
         case WEB_cornsilk:
            return "WEB_cornsilk";
         case WEB_crimson:
            return "WEB_crimson";

         case WEB_darkblue:
            return "WEB_darkblue";
         case WEB_darkcyan:
            return "WEB_darkcyan";
         case WEB_darkgoldenrod:
            return "WEB_darkgoldenrod";
         case WEB_darkgray:
            return "WEB_darkgray";
         case WEB_darkgreen:
            return "WEB_darkgreen";
         case WEB_darkkhaki:
            return "WEB_darkkhaki";
         case WEB_darkmagenta:
            return "WEB_darkmagenta";
         case WEB_darkolivegreen:
            return "WEB_darkolivegreen";
         case WEB_darkorange:
            return "WEB_darkorange";
         case WEB_darkorchid:
            return "WEB_darkorchid";
         case WEB_darkred:
            return "WEB_darkred";
         case WEB_darksalmon:
            return "WEB_darksalmon";
         case WEB_darkseagreen:
            return "WEB_darkseagreen";
         case WEB_darkslateblue:
            return "WEB_darkslateblue";
         case WEB_darkslategrey:
            return "WEB_darkslategrey";
         case WEB_darkturquoise:
            return "WEB_darkturquoise";
         case WEB_darkviolet:
            return "WEB_darkviolet";
         case WEB_firebrick:
            return "";
         case WEB_floralwhite:
            return "";
         case WEB_forestgreen:
            return "";
         case WEB_gainsboro:
            return "";
         case WEB_ghostwhite:
            return "";
         case WEB_gold:
            return "";
         case WEB_goldenrod:
            return "";
         case WEB_green:
            return "";
         case WEB_greenyellow:
            return "";
         case WEB_grey:
            return "";
         case WEB_honeydew:
            return "";
         case WEB_hotpink:
            return "";
         case WEB_indianred:
            return "";
         case WEB_indigo:
            return "";
         case WEB_ivory:
            return "";
         case WEB_khaki:
            return "";
         case WEB_lavender:
            return "";
         case WEB_lavenderblush:
            return "";
         case WEB_lawngreen:
            return "";
         case WEB_lemonchiffon:
            return "";
         case WEB_lightblue:
            return "";
         case WEB_lightcoral:
            return "";
         case WEB_lightcyan:
            return "";
         case WEB_lightgoldenrodyellow:
            return "";
         case WEB_lightgray:
            return "";
         case WEB_lightpink:
            return "";
         case WEB_lightsalmon:
            return "";
         case WEB_lightseagreen:
            return "";
         case WEB_lightskyblue:
            return "";
         case WEB_lightslategrey:
            return "";
         case WEB_lightsteelblue:
            return "";
         case WEB_lightyellow:
            return "";
         case WEB_lime:
            return "";
         case WEB_limegreen:
            return "";
         case WEB_linen:
            return "";
         case WEB_magenta:
            return "";
         case WEB_maroon:
            return "";
         case WEB_mediumaquamarine:
            return "";
         case WEB_mediumblue:
            return "";
         case WEB_mediumorchid:
            return "";
         case WEB_mediumpurple:
            return "";
         case WEB_mediumseagreen:
            return "";
         case WEB_mediumslateblue:
            return "";
         case WEB_mediumspringgreen:
            return "";
         case WEB_mediumturquoise:
            return "";
         case WEB_mediumvioletred:
            return "";
         case WEB_midnightblue:
            return "";
         case WEB_mintcream:
            return "";
         case WEB_mistyrose:
            return "";
         case WEB_moccasin:
            return "";
         case WEB_navajowhite:
            return "";
         case WEB_navy:
            return "";
         case WEB_oldlace:
            return "";
         case WEB_olive:
            return "";
         case WEB_olivedrab:
            return "";
         case WEB_orange:
            return "";
         case WEB_orangered:
            return "";
         case WEB_orchid:
            return "";
         case WEB_palegoldenrod:
            return "";
         case WEB_palegreen:
            return "";
         case WEB_paleturquoise:
            return "";
         case WEB_palevioletred:
            return "";
         case WEB_papayawhip:
            return "";
         case WEB_peachpuff:
            return "";
         case WEB_peru:
            return "";
         case WEB_pink:
            return "";
         case WEB_plum:
            return "";
         case WEB_powderblue:
            return "";
         case WEB_purple:
            return "";
         case WEB_red:
            return "";
         case WEB_rosybrown:
            return "";
         case WEB_royalblue:
            return "";
         case WEB_saddlebrown:
            return "";
         case WEB_salmon:
            return "";
         case WEB_sandybrown:
            return "";
         case WEB_seagreen:
            return "";
         case WEB_seashell:
            return "";
         case WEB_sienna:
            return "";
         case WEB_silver:
            return "";
         case WEB_skyblue:
            return "";
         case WEB_slateblue:
            return "";
         case WEB_slategrey:
            return "";
         case WEB_snow:
            return "";
         case WEB_springgreen:
            return "";
         case WEB_tan:
            return "";
         case WEB_teal:
            return "";
         case WEB_thistle:
            return "";
         case WEB_tomato:
            return "";
         case WEB_turquoise:
            return "";
         case WEB_violet:
            return "";
         case WEB_wheat:
            return "";
         case WEB_white:
            return "";
         case WEB_whitesmoke:
            return "";
         case WEB_yellow:
            return "";
         case WEB_yellowgreen:
            return "";
         default:
            return null;

      }
   }

   /**
    * English Name of Base Color
    * @param rgb
    * @return null if color is not a base color as defined in {@link IColorsBase}
    */
   public static String getName(int rgb) {
      rgb = ColorUtils.setAlpha(rgb, 0);
      switch (rgb) {
         case BASE_00_BLACK:
            return "Black";
         case BASE_01_WHITE:
            return "White";
         case BASE_02_RED:
            return "Red";
         case BASE_03_GREEN:
            return "Green";
         case BASE_04_BLUE:
            return "Blue";
         case BASE_05_YELLOW:
            return "Yellow";
         case BASE_06_MAGENTA:
            return "Magenta";
         case BASE_07_CYAN:
            return "Cyan";
         case BASE_08_GREY:
            return "Grey";
         case BASE_09_MAROON:
            return "Maroon";
         case BASE_10_GREEN_DARK:
            return "GreenDark";
         case BASE_11_BLUE_DARK:
            return "BlueDark";
         case BASE_12_OLIVE:
            return "Olive";
         case BASE_13_PURPLE:
            return "Purple";
         case BASE_14_TEAL:
            return "Teal";
         case BASE_15_BLUE_ELEC:
            return "BleuElec";
         case BASE_16_PINK_BLUSH:
            return "PinkBlush";
         case BASE_17_YELLOW_DOLLY:
            return "Dolly";
         case BASE_18_BLUE_MALIBU:
            return "Malibu";
         case BASE_19_GREEN_MINT:
            return "GreenMint";
         case BASE_20_CORAL_LIGHT:
            return "CoralLight";
         case BASE_21_CHARTREUSE:
            return "Chartreuse";
         case BASE_22_INDIGO_ELEC:
            return "IndigoElec";
         case BASE_23_BLUE_AZURE:
            return "BleuAzure";
         case BASE_24_ORANGE:
            return "Orange";
         case BASE_25_PINK_DEEP:
            return "PinkDeep";
         case BASE_26_GREEN_SPRING:
            return "GreenSpring";
         case BASE_27_WHITE_SMOKE:
            return "WhiteSmoke";
         case BASE_28_SILVER:
            return "Silver";
         case BASE_29_GREY_MICE:
            return "GreyMice";
         case BASE_30_GREY_CONCRETE:
            return "GreyConcret";
         case BASE_31_GREY_BEBE:
            return "GreyBebe";

         default:
            return null;
      }
   }

}
